### ISSUE TITLE
Retrieve a scene list for a known scene-name

### ISSUE THREAD

**Issue by artdevgame** [obs-websocket/obs-websocket#817]
##### Issue type
- Feature request

##### Description
I would like to be able to access all scenes for a scene list without having to switch to that scene first. Is that possible?

I imagine it using the current `GetSceneList` method, but it would allow me to provide an optional scene name
https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getscenelist

##### Technical information
- **Operating System** : Windows
- **OBS Studio version** : 27.0.1 (64 Bit)
- **obs-websocket version** : 4.7.0

**Comment by tt2468** [comment]
I don't understand what you are trying to get, can you please rephrase what you are wanting?

**Comment by artdevgame** [comment]
Hey @tt2468 👋🏻 

Sorry for the delay.

Let me illustrate with a tiny video of what I'm trying to achieve:

https://user-images.githubusercontent.com/353729/134772913-abb88354-8063-4714-8882-8b327ef6fcd4.mp4

My UI allows a user to select a scene collection and then select a scene from within that collection.

The two parts of the API protocol I'm using are: 
- [`ListSceneCollections`](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#listscenecollections), to get the list of scene collections in the first dropdown
- [`GetSceneList`](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#getscenelist), to get the list of scenes in the second dropdown

It seems like `GetSceneList` only uses the currently active scene, which means that regardless of whichever option I choose in the first dropdown, I can't get a list of options to populate the second dropdown.

This is illustrated in the video labelled `1`.

I've found a workaround, illustrated in the video with the label `2`, but it involves calling `SetCurrentScene` to change the active scene in OBS after selecting an option in the first dropdown, I then listen for the `SceneCollectionChanged` event to know to update the options in dropdown 2.

My original request was to adjust `GetSceneList` so that it accepts a scene name, and then I could avoid the dance of having to set the current scene (which would impact a live stream) first.

Thank you for your time.

**Comment by tt2468** [comment]
`but it involves calling SetCurrentScene to change the active scene in OBS after selecting an option in the first dropdown`

Do you mean `SetCurrentSceneCollection`? Scene collections are collections of scenes you can switch through. Scenes are items within a scene collection. It sounds like you are saying `scene` in places when you mean `scene collection`

**Comment by artdevgame** [comment]
I did mean `SetCurrentSceneCollection`, apologies for the confusion.

Perhaps it's more helpful if I write it as a question rather than request.

After getting a list of scene collections with `ListSceneCollections`, how do I get a list of scenes for each item in the collection?

**Comment by tt2468** [comment]
Unfortunately getting the scene list in a collection is not possible without switching to it first. This would require OBS's UI code to be mostly rewritten.

**Comment by pathum1** [comment]
> I did mean `SetCurrentSceneCollection`, apologies for the confusion.
> 
> Perhaps it's more helpful if I write it as a question rather than request.
> 
> After getting a list of scene collections with `ListSceneCollections`, how do I get a list of scenes for each item in the collection?

Did you find a proper solution to this issue @artdevgame ?

**Comment by tt2468** [comment]
@pathum1 As I stated above your comment, this is not possible in any way other than switching to the scene collection first.
