### ISSUE TITLE
Websocket connection on windows 11

### ISSUE THREAD

**Issue by JoeGillian8** [obs-websocket/obs-websocket#845]
##### Issue type
Connection is not made

##### Description
I am using websocket with obs to control the touch Portal application under windows 10 everything works correctly and since the switch to windows 11 the connection between touch portal and obs via the websocket no longer takes place. Touch Portal manages the other applications like Spotify, discord or other well but no more connection with OBS.
Has version 4.9 been tested on windows 11?

**Comment by tt2468** [comment]
Please use the full issue template.. We need to know your OBS version and have a log file.

**Comment by dungi** [comment]
I have the same issue. No connection to websocket since win11

**Comment by tt2468** [comment]
Closing this issue since OP failed to update theirs. If you are having this issue, please fill out a new issue with the template.

**Comment by gabo518** [comment]
tengo un problema desde que instale windows 11 y es que SAMMI no reconoce el teclado, para editar los comandos si pero luego al momento de canjear los puntos no ejecuto los comando de simulacion de teclado, ayuda
